functional:
  - Пользователь должен иметь возможность просматривать каталог товаров и видеть их названия, рейтинги и цены.
  - Пользователь должен иметь возможность фильтровать товары по различным критериям (категория, цена, рейтинг и т.д.).
  - Пользователь должен иметь возможность добавлять товары в корзину.
  - Пользователь должен иметь возможность просматривать содержимое корзины, включая возможность редактирования (удаление товаров).
  - Пользователь должен иметь возможность оформлять заказ и переходить на страницу оплаты.
  - Пользователь должен иметь возможность искать товары по ключевым словам.
  - Пользователь должен иметь возможность просматривать подробную информацию о каждом товаре.

non-functional:
  - Сайт должен быть оптимизирован для быстрого времени загрузки и отзывчивости на мобильных устройствах.
  - Сайт должен быть безопасным и защищать данные пользователей, включая использование шифрования для передачи данных.
  - Сайт должен поддерживать большое количество одновременных пользователей без снижения производительности.

implicit:
  - Интерфейс сайта должен быть интуитивно понятным и легким для навигации.
  - Сайт должен обеспечивать устойчивое и надежное функционирование, минимизируя время простоя и ошибки.
  - Дизайн сайта должен быть адаптивным, чтобы обеспечить удобство на различных разрешениях экрана.
  - Сайт должен учитывать доступность для пользователей с ограниченными возможностями.
